name: Sync Issues

on:
  push:
    branches:
      - development
  schedule:
    - cron: '15 * * * *' # every hour at minute 15 (github recommends to set such cron jobs not at the start of an hour)

jobs:
  sync-issues:
    name: Sync Issues
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.14.1"

      - name: Yarn Install
        run: yarn install --mode=skip-build

      - name: Get GitHub App token
        uses: tibdex/github-app-token@v1.7.0
        id: get_installation_token
        with:
          app_id: ${{ secrets.UBIQUITY_BOUNTY_BOT_APP_ID }}
          private_key: ${{ secrets.UBIQUITY_BOUNTY_BOT_PRIVATE_KEY }}

      - name: Sync Issues
        env:
          DEVPOOL_GITHUB_API_TOKEN: ${{ steps.get_installation_token.outputs.token }}
        run: npx tsx index.ts
